type Todo {
	deadline: String
	isUrgent: Boolean
	isDone: Boolean!
	notes: String
	title: String!
	userId: String
	list: List
}

type List {
	icon: String
	isCustom: Boolean
	title: String!
	userId: String
}

type Query {
	getTodos: [Todo!]
	findTodosByUser(userId: String!): [Todo!]
	getLists: [List!]
	findListsByUser(userId: String!): [List!]
	findDefaultLists(isCustom: Boolean!): [List!]
}
